jqassistant:
  plugins:
    - group-id: org.jqassistant.plugin
      artifact-id: jqassistant-spring-plugin
      version: 2.0.0
    - group-id: org.jqassistant.contrib.plugin
      artifact-id: jqassistant-jmolecules-plugin
      version: 1.4.0
  analyze:
    rule:
      default-concept-severity: INFO
    groups:
      - jmolecules-ddd:Strict
      - jmolecules-hexagonal:Default
      - spring-boot:Strict
      - maven:Default
