@startuml

folder adapters {
  folder primary {
    interface UserApi <<REST>> <<OpenApi>> <<Generated>>
    class UserController <<Primary Adapter>>
  }
  folder secondary {
    class UserRepositoryImpl <<Secondary Adapter>> <<Spring Data JPA>>
  }
}

folder domain {
  class UserApplicationService <<Primary Port>>
  class UserDomainService <<Service>>
  interface UserRepository <<Secondary Port>>
}

UserApi <|-down- UserController
UserController -down-> UserApplicationService
UserApplicationService -down-> UserDomainService
UserDomainService -> UserRepository
UserRepository <|- UserRepositoryImpl

@enduml