---
name: CI

on:
  push:
    branches:
      - main
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

concurrency:
  group: build-java-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: ts-graphviz/setup-graphviz@v1
  build:
    needs: prepare
    uses: jqassistant-tooling/jqassistant-github-actions/.github/workflows/ci.yml@main
    with:
      java_test_versions: '[25]' # use versions supported by Spring
      publish_snapshots: false
    secrets:
      ossrh_username: ${{ secrets.OSSRH_USERNAME }}
      ossrh_password: ${{ secrets.OSSRH_PASSWORD }}
      ossrh_signing_key: ${{ secrets.OSSRH_SIGNING_KEY }}
      ossrh_signing_password: ${{ secrets.OSSRH_SIGNING_PASSWORD }}
      sonar_token: ${{ secrets.SONAR_TOKEN }}